
version: 2

models:
  - name: stg_students
    description: 'This table contains the information of students like their name, gender, email etc.'
    columns:
      - name: student_id
        description: 'This is a primary key(unique identifier for each row) in this table.'
        tests:
          - not_null
          - unique
      - name: name
        description: 'Name of Student.'
      - name: gender
        description: 'Gender of student.'
        tests:
          - accepted_values:
              values: ['Female', 'Male', 'Unknown']
      - name: age 
        description: 'Age of student.'
        tests:
          - values_between_range:
              min_value: 13
              max_value: 75
      - name: contact_no
        description: 'Contact number or Mobile number of student.'
      - name: email
        description: 'Email address of student.'
      - name: city
        description: 'City of students where they live.'
      - name: state
        description: 'State of students where they belongs like Uttar Pradesh, Madhya Pradesh, Bihar etc.'
      - name: preferred_language
        description: 'preferred language by student like Hinid, English etc.'
      - name: connect_with
        description: 'Name of the counsellor who enrolled student.'
      - name: registered_date
        description: 'Date of enrollment when student enrolled first time into Geeta Samagam.'
  
  - name: stg_exams
    description: Information or data of exams such as exam's name, exam's duration and exam's date
    columns:
      - name: exam_id 
        description: Primary key or unique identifier for each row in exams table
        tests:
          - not_null
          - unique
      - name: exam_name
        description: Name of exam such as Vedanta Samhita, Sant Sarita, Bhagavad Geeta etc.
        tests:
          - accepted_values:
              values: ['Vedanta Samhita', 'Shoonyata Saptaty', 'Bhagavad Geeta', 'Sant Sarita', 'Ashtavakra Geeta', 'Bodh Pratyusha']
      - name: exam_duration_in_minutes
        description: Duration of exam in minutes
        tests:
          - column_value_is_equal:
              value: 60
      - name: exam_date
        description: Date of exam 

  - name: stg_results
    description: This table contains student's result like their correct answer, percentile, percentage etc.
    columns:
      - name: result_id
        description: Primary key or unique identifier for each row in this table.
        tests:
          - not_null
          - unique
      - name: exam_id
        description: Unique id for each exam 
      - name: student_id
        description: Unique id for each student
      - name: total_question
        description: Number of question asked in the exam
        tests:
          - column_value_is_equal: 
              value: 25
      - name: correct_answer
        description: Number of questions are correct of student
        tests:
          - values_between_range:
              min_value: 0
              max_value: 25
      - name: percentile
        description: Percentile of student that scored in a particular exam
        tests: 
          - values_between_range:
              min_value: 0
              max_value: 100
      - name: percentage
        description: Percentage of student that scored in a particular exam
        tests: 
          - values_between_range:
              min_value: 0
              max_value: 100
      - name: completion_time_in_minutes
        description: Amount of time taken by student to complete exam
        tests: 
          - values_between_range:
              min_value: 0
              max_value: 60
      - name: completion_date
        description: Date when exam was completed


      
